language: csharp

matrix:
    include:
        - dotnet: 2.1
          mono: latest

solution: vstest.coverage.sln

script:
    - dotnet --info
    - dotnet pack
    - dotnet test src/Coverage.Report.Tests/Coverage.Report.Tests.csproj
    - dotnet test src/CodeCoverageToLcovConverterTests/CodeCoverageReaderTests.csproj
